name: Upload public site

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]
    paths: public

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upload-files:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        service_account: 'github-deployer@keen-electron-277310.iam.gserviceaccount.com'
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: '/public/'
        destination: 'keen-electron-277310.appspot.com/status-page/'
        predefinedAcl: publicRead